application: google.com:theme-park-queues-demo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api
  static_dir: serverside

- url: /
  static_files: clientside/index.html
  upload: clientside/index.html

- url: /
  static_dir: clientside



